name: language server release

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    permissions:
      contents: write  # for ncipollo/release-action to create a release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup jdk-21
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        java-version: 21
        distribution: 'adopt'

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libgc1 libgc-dev shellcheck asciidoc asciidoctor ruby-asciidoctor-pdf pcregrep antlr4

    - name: build release
      run: lsp/release

    - name: Read VERSION file
      id: getversion
      run: echo "::set-output name=version::$(cat version.txt)"

    - uses: ncipollo/release-action@bcfe5470707e8832e12347755757cec0eb3c22af # v1.18.0
      with:
        artifacts: "build/fuzion_language_server_${{ steps.getversion.outputs.version }}.zip"
        tag: "v${{ steps.getversion.outputs.version }}"
        prerelease: false
        generateReleaseNotes: true
        token: ${{ secrets.GITHUB_TOKEN }}
