# This file is part of the Fuzion language implementation.
#
# The Fuzion language implementation is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, version 3 of the License.
#
# The Fuzion language implementation is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License along with The
# Fuzion language implementation.  If not, see <https://www.gnu.org/licenses/>.


# -----------------------------------------------------------------------
#
#  Tokiwa Software GmbH, Germany
#
#  GitHub Actions workflow to build and test Fuzion on Ubuntu.
#
# -----------------------------------------------------------------------

name: run tests on linux

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1-5' # monday through friday

env:
  PRECONDITIONS: true
  POSTCONDITIONS: true
  FUZION_REPRODUCIBLE_BUILD: true
  dev_flang_tools_serializeFUIR: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.value }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install sqlite3 libgc1 libgc-dev shellcheck asciidoc asciidoctor ruby-asciidoctor-pdf pcregrep antlr4 libclang1 libclang-dev

      - name: link libclang
        run: |
          export CLANG_MAJOR_VERSION=$(clang --version | head -n 1 | awk '{print $4}' | cut -d. -f1)
          test -f /usr/lib/llvm-$CLANG_MAJOR_VERSION/lib/libclang.so && sudo ln -s /usr/lib/llvm-$CLANG_MAJOR_VERSION/lib/libclang.so /usr/lib/

      - name: check shell scripts
        run: make shellcheck

      - name: build java code
        run: make javac

      - name: build (no java modules)
        run: make no-java

      - name: build docs
        run: make doc

      - name: syntax check
        run: make syntaxcheck

  run_tests:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        backend: ["jvm", "c", "int"]
    steps:

      - name: run tests
        run: make run_tests_${{ matrix.backend }}_parallel

